Repository EKEC-crew/BE, pull requests merged in 2025-08, with the labels that each got.

#129 크루 일정 CRUD 및 댓글 CRUD 테스트 완료
  prisma/schema.prisma
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
Labels: :sparkles: feature

#195 ✨ 크루 일정 신청 및 좋아요 기능 구현
  prisma/schema.prisma
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
  src/error.js
Labels: :sparkles: feature

#199 ✨ 크루 일정 신청 및 좋아요 기능 구현
  prisma/schema.prisma
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
  src/error.js
Labels: :sparkles: feature

#204 Reapply "✨ 크루 일정 신청 및 좋아요 기능 구현"
  prisma/schema.prisma
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
  src/error.js
Labels: :bug: bug

#222 :recycle: 일정 모든 responsedto에 userId 추가
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/service/plan.service.js
Labels: :recycle: refactor

#228 :recycle: 좋아요개수랑 댓글 개수 추가
  src/crew/page/plan/repository/plan.repository.js
Labels: :recycle: refactor

#229 :recycle: 응답 dto에 좋아요개수랑 댓글 개수 추가
  src/crew/page/plan/repository/plan.repository.js
Labels: :recycle: refactor

#233 ♻️Refactor: 크루 지원/승낙 수정 & apply userId -> JWT 토큰 기반으로 수정
  src/crew/apply/controller/apply.controller.js
  src/crew/apply/dto/request/apply.request.dto.js
  src/crew/apply/dto/response/apply.response.dto.js
  src/crew/apply/middleware/crew.middleware.js
  src/crew/apply/repository/apply.repository.js
  src/crew/apply/route/apply.route.js
  src/crew/apply/service/apply.service.js
Labels: :recycle: refactor

#237 :recycle: isLiked, isApplied 필드 추가
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/service/plan.service.js
Labels: :recycle: refactor

#269 :sparkles: 다가오는 일정 api 구현
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
Labels: :sparkles: feature

#270 ✨ 다가오는 일정 api 구현
  src/crew/page/notice/notice-comment.service.js
  src/crew/page/notice/notice.comment.service.js
  src/crew/page/notice/notice.service.js
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
  src/crew/page/post/controller/post.controller.js
  src/crew/page/post/dto/response/post.response.dto.js
Labels: :sparkles: feature

#281 :recycle: writerImage 필드 추가
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
Labels: :recycle: refactor

#295 :recycle: 일정 댓글 오름차순으로 변경
  src/crew/page/plan/repository/plan.repository.js
Labels: :recycle: refactor

#296 :recycle: 일정 댓글 오름차순으로 변경
  README.md
  assets/BE_Architecture.png
  assets/branch_strategy.png
  assets/icon.webp
  src/crew/apply/joined/controller/joined.controller.js
  src/crew/apply/joined/dto/request/joined.request.dto.js
  src/crew/apply/joined/dto/response/joined.response.dto.js
  src/crew/apply/joined/repository/joined.repository.js
  src/crew/apply/joined/route/joined.route.js
  src/crew/apply/joined/service/joined.service.js
  src/crew/apply/route/apply.route.js
  src/crew/page/plan/repository/plan.repository.js
Labels: :recycle: refactor

#316 :recycle: 비로그인 회원도 일정, 댓글 조회 가능으로 수정
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
Labels: :recycle: refactor

#317 :recycle: Refactor: isLiked 사용자 좋아요 여부 추가
  src/crew/page/post/controller/post.controller.js
  src/crew/page/post/dto/request/post.request.dto.js
  src/crew/page/post/dto/response/post.response.dto.js
  src/crew/page/post/repository/post.repository.js
  src/crew/page/post/route/post.route.js
  src/crew/page/post/service/post.service.js
Labels: :sparkles: feature

#339 :recycle: 크루장도 다가오는 일정 리스트 조회 가능하게끔 수정
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/service/plan.service.js
Labels: :recycle: refactor

#340 :recycle: 크루장도 다가오는 일정 리스트 조회 가능하게끔 수정
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/service/plan.service.js
Labels: :recycle: refactor
