Repository EKEC-crew/BE, pull requests merged in 2025-07, with the labels that each got.

#17 :recycle: Refactor: 크루 검색 필터 #16
  src/crew/search/search/controller/search.controller.js
Labels: :recycle: refactor

#22 🐛Fix: CI/CD 파이프라인 수정
  .github/workflows/deploy-main.yml
Labels: :bug: bug

#65 ✨ 크루 댓글 생성 기능 구현
  prisma/schema.prisma
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/repository/plan.repository.js
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
Labels: :sparkles: feature

#68 :sparkles: 크루 댓글 기능 구현
  src/crew/page/plan/route/plan.route.js
  src/crew/page/plan/service/plan.service.js
Labels: :sparkles: feature

#73 Swagger 오류 해결
  src/crew/page/plan/controller/plan.controller.js
  src/crew/page/plan/dto/request/plan.request.dto.js
  src/crew/page/plan/dto/response/plan.response.dto.js
  src/crew/page/plan/route/plan.route.js
Labels: :bug: bug

#79 🐛 404, 202 응답 간소화
  src/crew/page/plan/controller/plan.controller.js
Labels: :bug: bug
